### ISSUE TITLE
Cannot find YamlParser or DataClassDecoder at runtime

### ISSUE THREAD

**Issue by nicholasgrose** [sksamuel/hoplite#305] opened 2022-05-09 04:53 UTC
I am using Kotlin 1.6.21 with Intellij IDEA 2022.1 and Hoplite 2.0.4.
My Gradle is version 7.4.2, and I am compiling into a fat jar via [the gradle shadow jar plugin](https://github.com/johnrengelman/shadow) version 7.1.2.

I have been working on a Minecraft plugin that loads its configurations from a YAML file via Hoplite. I bundle all dependencies via shadow because including them as a separate JAR would be inconvenient for somebody downloading the plugin. In my code, I load my configuration as follows:
```kotlin
val config = ConfigLoaderBuilder.default()
                .addDecoder(CommonDecoder())
                .addResourceSource(path.toString())
                .build()
                .loadConfigOrThrow<Config>()
```

However, during runtime, I encounter the following error:
```
[00:31:36 INFO]: [Gateway] Configuration failed to load: Error loading config because:

    Could not detect parser for file extension '.yaml' - available parsers are {}

    Could not find config file plugins\Gateway\config.yaml
```

I have both hoplite-core and hoplite-yaml including in my build.gradle.kts. I am aware of both #94 and #204, however, merging service files does not appear to be solving the issue for me. This error will occur, in some form, even when I add the YamlParser manually. In that case, it instead complains about being unable to find the DataClassDecoder, and recommends merging services if using a fat jar. This, though, is already being done. In my build.gradle.kts, I am doing this:
```kotlin
shadowJar {
        archiveBaseName.set(rootProject.name)
        archiveClassifier.set("")
        archiveVersion.set(rootProject.version.toString())
        mergeServiceFiles()
    }
```

Regardless of the inclusion, the error still occurs during runtime, even when conducting a clean build. My resultant jar always looks like this, even when merging service files: 
![image](https://user-images.githubusercontent.com/35816886/167342003-881349ed-8833-48b6-a509-3697900f6a31.png)

I've tried every variation of merging services I can think of, but to no avail. Any ideas would be greatly appreciated. Thank you for your time. I apologize if the fix is something particularly obvious that I may have missed; my familiarity with the construction of JAR files is limited.

**Comment by sksamuel** [comment] 2022-05-09 10:17
What's the content of those two service files,

**Comment by nicholasgrose** [comment] 2022-05-09 14:21
Within parsers.Parser, it only contains:
```
com.sksamuel.hoplite.yaml.YamlParser
com.sksamuel.hoplite.parsers.PropsParser
```

In decoder.Decoder:
```
com.sksamuel.hoplite.decoder.UUIDDecoder
com.sksamuel.hoplite.decoder.LocalDateDecoder
com.sksamuel.hoplite.decoder.LocalDateTimeDecoder
com.sksamuel.hoplite.decoder.LocalTimeDecoder
com.sksamuel.hoplite.decoder.InstantDecoder
com.sksamuel.hoplite.decoder.DurationDecoder
com.sksamuel.hoplite.decoder.KotlinDurationDecoder
com.sksamuel.hoplite.decoder.PeriodDecoder
com.sksamuel.hoplite.decoder.SqlTimestampDecoder
com.sksamuel.hoplite.decoder.EnumDecoder
com.sksamuel.hoplite.decoder.StringDecoder
com.sksamuel.hoplite.decoder.IntDecoder
com.sksamuel.hoplite.decoder.FloatDecoder
com.sksamuel.hoplite.decoder.DoubleDecoder
com.sksamuel.hoplite.decoder.ShortDecoder
com.sksamuel.hoplite.decoder.ByteDecoder
com.sksamuel.hoplite.decoder.BooleanDecoder
com.sksamuel.hoplite.decoder.RegexDecoder
com.sksamuel.hoplite.decoder.LongDecoder
com.sksamuel.hoplite.decoder.ListDecoder
com.sksamuel.hoplite.decoder.SortedSetDecoder
com.sksamuel.hoplite.decoder.SetDecoder
com.sksamuel.hoplite.decoder.LinkedHashMapDecoder
com.sksamuel.hoplite.decoder.MapDecoder
com.sksamuel.hoplite.decoder.FileDecoder
com.sksamuel.hoplite.decoder.SizeInBytesDecoder
com.sksamuel.hoplite.decoder.PathDecoder
com.sksamuel.hoplite.decoder.BigIntegerDecoder
com.sksamuel.hoplite.decoder.BigDecimalDecoder
com.sksamuel.hoplite.decoder.PrincipalDecoder
com.sksamuel.hoplite.decoder.InetAddressDecoder
com.sksamuel.hoplite.decoder.URLDecoder
com.sksamuel.hoplite.decoder.KClassDecoder
com.sksamuel.hoplite.decoder.URIDecoder
com.sksamuel.hoplite.decoder.SecretDecoder
com.sksamuel.hoplite.decoder.TripleDecoder
com.sksamuel.hoplite.decoder.PairDecoder
com.sksamuel.hoplite.decoder.YearDecoder
com.sksamuel.hoplite.decoder.MonthDayDecoder
com.sksamuel.hoplite.decoder.JavaUtilDateDecoder
com.sksamuel.hoplite.decoder.IntRangeDecoder
com.sksamuel.hoplite.decoder.LongRangeDecoder
com.sksamuel.hoplite.decoder.CharRangeDecoder
com.sksamuel.hoplite.decoder.YearMonthDecoder
com.sksamuel.hoplite.decoder.MinutesDecoder
com.sksamuel.hoplite.decoder.SecondsDecoder
com.sksamuel.hoplite.decoder.InlineClassDecoder
com.sksamuel.hoplite.decoder.SealedClassDecoder
com.sksamuel.hoplite.decoder.DataClassDecoder
```

Both appear to contain the relevant classes, if I'm not mistaken. DataClassDecoder is the final decoder listed, and YamlParser is the first parser.

**Comment by sksamuel** [comment] 2022-05-09 14:46
So the service files are being merged properly, but yet it is not finding any.
Do you have a full example I can run ?

**Comment by nicholasgrose** [comment] 2022-05-09 19:10
Update on this issue. I was wondering if something had gone awry as a result of my application existing as a Paper plugin for Minecraft. After chatting with a helpful person on the Paper Discord, I discovered that each plugin has a specific ClassLoader it needs to access. Normally that loader is set properly, however a quirk in my code led to the configuration being loaded outside of that context.

Thus, the ClassLoader that Hoplite used (attached to the current thread) when loading its services was incorrect, and it failed to fetch the services. With some modifications involving some temporary context switching, I have been able to guarantee that loader is correct, and Hoplite is working as expected.

I will need to fix other areas of the code to prevent the hack-y context switching, but for now it functions as expected.

**Comment by sksamuel** [comment] 2022-05-09 20:00
The config builder also allows you to specify the class loader, so you could use that to pass in the one from minecraft.

**Comment by nicholasgrose** [comment] 2022-05-09 20:18
Where is that specified in the config builder? It appears to be private in the ConfigLoaderBuilder, and using ConfigLoaderBuilder.empty { ... } still does not appear to allow access to the classLoader, even if it is a var.

**Comment by nicholasgrose** [comment] 2022-05-23 15:51
Just wanting to keep this alive for future users with my issue. How exactly does one switch the class loader used inside of the ConfigLoaderBuilder besides temporarily changing it in the current thread, itself? The property for it does not appear to be accessible.

**Comment by sksamuel** [comment] 2022-05-23 17:05
I've released 2.1.5 which has a withClassLoader option on the config loader builder.

**Comment by sksamuel** [comment] 2022-05-25 11:57
@nicholasgrose did this fix your problem

**Comment by nicholasgrose** [comment] 2022-05-25 15:21
It did! Thank you so much! One final note is that it feels slightly weird needing to use `.empty()` followed by `.withClassLoader()` and all then `.addDefault*()`. It works wonderfully, it just feels less concise than `.default()` followed by `.withClassLoader()` or the reverse.

**Comment by vie10** [comment] 2022-06-05 04:35
> It did! Thank you so much! One final note is that it feels slightly weird needing to use `.empty()` followed by `.withClassLoader()` and all then `.addDefault*()`. It works wonderfully, it just feels less concise than `.default()` followed by `.withClassLoader()` or the reverse.

The problem is caused to the bad structuring of Bukkit, hence when you're using builder, first of all, you need to use the `.withClassLoader()`, then follow it with `.addDefaults()`. This way the config builder will be able to find decoders in your plugin classpath.

So it isn't problem of the library, it's a Bukkit problem.

**Comment by sksamuel** [comment] 2022-06-05 05:57
What is bukkit ?

**Comment by vie10** [comment] 2022-06-05 08:27
> What is bukkit ?

A wrapper around Minecraft server for extend it with plugins. It's irrelevant to this Library. I think you can close this issue, the withClassloader fixes this problem.

**Comment by sksamuel** [comment] 2022-06-05 13:18
Ok thanks

**Closed by sksamuel** 2022-06-05 13:18 UTC
